(ns mbstats-figrum.stats)
(defn- zero[] (atom 0))
(def statkeys [:intro :extro :intui :sense :judge :perce :think :feel])
(defrecord Stat   [title    letter  label opposite-label value])
(def intro (Stat. "Introvert" "I"   :intro :extro        (zero)))
(def extro (Stat. "Extrovert" "E"   :extro :intro        (zero)))
(def judge (Stat. "Judging"   "J"   :judge :perce        (zero)))
(def perce (Stat. "Perceiving""P"   :perce :judge        (zero)))
(def intui (Stat. "Intuition" "N"   :intui :sense        (zero)))
(def sense (Stat. "Sensing"   "S"   :sense :intui        (zero)))
(def think (Stat. "Thinking"  "T"   :think :feel         (zero)))
(def feel  (Stat. "Feeling"   "F"   :feel  :think        (zero)))
(def allstats {
   :intro intro, :intui intui, :judge judge :think think
   :extro extro, :sense sense, :perce perce :feel  feel
               })

(defn title [label] (:title (allstats label))) 
(defn letter [label] (:letter (allstats label)))
(defn opposite [label] (:opposite-label (allstats label)))
(defn- atval [label] (:value (allstats label)))
(defn- setval [label val] (reset! (atval label) val))
(defn- set0 [label ] (setval label 0))
(defn reset-all [] (doall (map set0 statkeys)))
(defn change [label value]
   (setval (opposite label) (- 100  value))
   (setval label value )
  )
(defn retr [label] @(atval label))
(defrecord BigStat [title statlist link color])
;is
(def istp [:intro :sense :think :perce])
(def istj [:intro :sense :think :judge])
(def isfp [:intro :sense :feel :perce])
(def isfj [:intro :sense :feel :judge])
;in
(def intp [:intro :intui :think :perce])
(def intj [:intro :intui :think :judge])
(def infp [:intro :intui :feel :perce])
(def infj [:intro :intui :feel :judge])
;es
(def estp [:extro :sense :think :perce])
(def esfj [:extro :sense :feel :judge])
(def estj [:extro :sense :think :judge])
(def esfp [:extro :sense :feel :perce])
;en
(def entp [:extro :intui :think :perce])
(def enfj [:extro :intui :feel :judge])
(def entj [:extro :intui :think :judge])
(def enfp [:extro :intui :feel :perce])
;(defn- retr-sym [lab_s] (retr (keyword lab_s)))
(defn retr-seq [l] (map retr l))
(def sym-hack {:entp entp :isfj isfj})
(defn mb [lab] (reduce * (retr-seq (sym-hack lab))))
